### ISSUE TITLE
Spec failures on clean checkout

### ISSUE THREAD

**Issue by grncdr** [alisnic/solargraph-arc#25]
**Describe the bug**
rails6_spec fails on a fresh clone.

**To Reproduce**

1. Follow the steps in https://github.com/alisnic/solargraph-arc/blob/master/README.md#contributing
2. Run `rspec`

**Expected behavior**

Specs pass :)

**Actual behavior**

```
$ rspec -f failures
./spec/solargraph-arc/schema_spec.rb:31:generates methods based on schema
./spec/solargraph-arc/rails6_spec.rb:126:provides completions for ActionController::Base
./spec/solargraph-arc/rails6_spec.rb:8:it provides Rails controller api
./spec/solargraph-arc/rails6_spec.rb:115:provides completions for ActiveRecord::Base
./spec/solargraph-arc/rails6_spec.rb:93:provides completions for ActiveJob::Base
./spec/solargraph-arc/rails6_spec.rb:61:can auto-complete inside migrations
./spec/solargraph-arc/rails6_spec.rb:104:provides completions for ActionDispatch::Routing::Mapper
./spec/solargraph-arc/rails6_spec.rb:27:can auto-complete inside routes
./spec/solargraph-arc/rails6_spec.rb:44:can auto-complete inside mailers
```

Other info:

Related, but not identical to #18

**Comment by alisnic** [comment]
@grncdr can you please provide some info? Specifically
- Ruby version (`ruby -v`)
- Bundler version (`bundler -v`)
- full output of the test suite

**Comment by grncdr** [comment]
Hi @alisnic I was using ruby 2.7.5p203 and bundler 2.1.4

However this problem seems to be fixed now, doing a `git pull && bundle && rspec` shows no failures.
